INSERT INTO [HMB].[SQS].[ENG_BUILD_DATA]

( [ENG_CODE],[ENG_TYPE],[ENG_SN],[BLK_NO],[HEAD_NO],
[MODEL],[CC],[ENGINE_TYPE],[FUEL],[MT_AT],[NATION],
[AS],[ENGINE_OIL],[CKPS],[BLOCK],[CRK_SHT],[CYL_HEAD],
[HEAD_SUB],[CON_ROD],[PISTON],[OIL_PAN],[CVVT],[IN_VALVE],
[EX_VALVE],[TIMMING_CHAIN_COVER],[HEAD_COVER],[SPARK_PLUG],
[AUTO_MACHINE_PASS],[ALTERNATOR],[INMANI],[EXMANI],
[DAMPER_PULLEY],[HEAD_GASKET],[CHAIN_GUIDE],[TENSIONER],
[TIMING_CHAIN],[MLA],[WATER_PUMP],[HOUSING],[IG_COIL],
[D_PIPE],[INLET_FITTING],[VALVE_SPRING] )

--VALUES ( 'BB41','F3LAPL','060120',' ',' ',		<-- SE FOR INSERIR BLOCO OU HEAD EM BRANCO COLOCAR ESPAÇO: ' '
VALUES ( 'BB41','F3LAPL','999888',' ',' ',

'1','1','1','1','1','1','1','1','1','1',
'1','1','1','1','1','1','1','1','1','1',
'1','1','1','1','1','1','1','1','1','1',
'1','1','1','1','1','1','1','1' )

--MOSTRA OS RESULTADOS ATUALIZADOS NA TABELA ORDENADO PELO ID DECRESCENTE
SELECT TOP(100)[ID]
      ,[ENG_CODE]
      ,[ENG_TYPE]
      ,[ENG_SN]
      ,[BLK_NO]
      ,[HEAD_NO]
      ,[REG_DT]
      ,[REG_TM] FROM [HMB].[SQS].[ENG_BUILD_DATA]
ORDER BY ID DESC